### ISSUE TITLE
Map Design

### ISSUE THREAD

**Issue by amitferman** [Husky-Navigation-Services/Husky-Navigation#4]
Map design complete. A preview is available [here](https://api.mapbox.com/styles/v1/aferman/ckhvetwgy0bds19nznkfvodbx.html?fresh=true&title=view&access_token=pk.eyJ1IjoiYWZlcm1hbiIsImEiOiJja2ZrZXJvbjUwZW5wMnhxcjdyMXc3ZjRnIn0.WGdId2uO9XokPaJmaxlLXg)

Making changes is generally simple, so let me know if you have suggestions.

**Comment by dberezansky** [comment]
Looks good, I think there could be a few changes made after we decide the final UI. Otherwise looks good, good work!
