### ISSUE TITLE
Decision Module Review

### ISSUE THREAD

**Issue by dberezansky** [Husky-Navigation-Services/Husky-Navigation#5]
The decision module is working and in a completed state. That being said there is some things I hope to improve on. The most major of which is implementing Dijkstra's algorithm because the worst case runtime for our current iteration is something like V^2 and the worst case that seems to be optimal (I could be wrong) is Vlog|V|. For now I am weighing the pros and cons of changing things around to Dijkstra's algorithm which would involve implementing priority queue or something like that. Any thoughts on whether this is worth pursuing, ideas for pros and cons? Will this work okay with our existing modules?

**Comment by amitferman** [comment]
I haven't done test-cases, but it seems like it will work, though it looks more like Depth-First-Search adapted to weighted graphs. I suspect that it's time complexity is therefore exponential because if you have V nodes and E neighbors per node, then the number of times you enter the recursive method is something of the order E^V.

**Comment by dberezansky** [comment]
Yeah I think I meant to write that. The time complexity should be E^V, I think I wrote the wrong thing down when I was working through (it was pretty late).

**Comment by amitferman** [comment]
Yeah, it works well enough for testing and for an initial end result. However, we might run into problems with runtime since each node doubles/triples/quadruples the runtime with the current algorithm, but that depends on the actual performance.

**Comment by dberezansky** [comment]
I guess we will see, I will most likely end up changing the algorithm later on but I think we are in a good place to do that. Either way I think for now we can mark the decision module as completed and come back to it later on. I might just fix it when I get some more time later to work on it (say tomorrow or after Tuesday).
