### ISSUE TITLE
Red Starting Marker to Red Circle

### ISSUE THREAD

**Issue by dberezansky** [Husky-Navigation-Services/Husky-Navigation#6]
I went ahead and changed the starting marker to a circle. I essentially separated the two markers by treating them as separate elements `startMarker` and `endMarker`. Currently the UI looks something like this:
![image](https://user-images.githubusercontent.com/23129330/100526870-0982ab00-3182-11eb-86b4-6b383d5ea8ed.png)
The main change is the inclusion of the red circle as the starting icon. The main issue I see is slight blurring on the edge of the circle for some reason but it seems to be getting better. This might be an "Edge Legacy" specific problem though. It seems to have been fixed in both browsers though. I guess we should just look out if this is a potentially recurring issue, so far I have no evidence that this is the case.
![image](https://user-images.githubusercontent.com/23129330/100526929-801fa880-3182-11eb-889e-a6a579c0a1bc.png)
The icon seems to be in the correct dimensions, any thoughts on whether we should change the starting marker further? How does it look overall for our UI?

**Comment by amitferman** [comment]
I'll probably edit the icon later in Gimp. Nice.

**Comment by amitferman** [comment]
Something broke with the icons on my end

**Comment by amitferman** [comment]
Oh nvm

**Comment by dberezansky** [comment]
Ah, what does it look like on your end?

**Comment by dberezansky** [comment]
Oh, @amitferman did it fix?

**Comment by amitferman** [comment]
Works now!

**Comment by dberezansky** [comment]
Nice, I am glad! How does it look compared to the previous version?
