### ISSUE TITLE
Decision Model

### ISSUE THREAD

**Issue by amitferman** [Husky-Navigation-Services/Husky-Navigation#7]
As I understand it, the method getShortestpath() gets the information needed to navigate from any Node A to any Node B, so it would be most efficient to call this method immediately after the Server is started so that the user has to wait less time. In the case that the user wants to use their current location, we can make the calculations by just re-calling the method with the new node. Thoughts?

**Comment by dberezansky** [comment]
`getShortestPath()` would be the private message called by the public method `getDecision()` which returns the total distance directly and by reference semantics technically returns the optimal path. Based on this information you can compute the estimated time of arrival. This means that the server has to call `getDecision()` not `getShortestPath()`.

**Comment by amitferman** [comment]
I'm aware, but calling `getDecision()` every time the user wants to navigate is redundant since it re-runs the algorithm each time when calling `getDecision() `once gives you all the information you need to navigate from any known location to any known location. So if `getDecision()` is called once, optimally before the user requests the navigation path, the back-end can just use the `getShortestPath()` method to more quickly return a result.

**Comment by amitferman** [comment]
Both methods would work, but using this one would make it so that the algorithm's exponential time complexity doesn't matter because the program should have a ton of time to complete the algorithm before the user requests the path, and `getShortestPath()` is very fast.

**Comment by dberezansky** [comment]
`getShortestPath()` needs to no the start id and end id in order to execute so it would need to be after the user requests a start and end point as I understand it. Nonetheless, you would still have to do the rest of what `getDecision()` is doing since the actual algorithm is done with the `Node.id` not the node itself after the user requests a path.

**Comment by amitferman** [comment]
But getDecision() returns the same result with any starting Node I believe

**Comment by dberezansky** [comment]
I am not sure if that is the case, as it is setting up the predecessors and distances for a particular node id.

**Comment by amitferman** [comment]
Oh whoops. I had it backward. `getShortestPath()`, I think, will produce the same values for `predecessors` and `distances` no matter which node it starts with.

**Comment by dberezansky** [comment]
We should meet and talk about this further.
